name:                tui
version:             0.0.0.0
github:              "NorfairKing/tui"
license:             MIT

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - brick
  - cursor
  - directory
  - mtl
  - vty

executables:
  tui:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - tui
